In [10]:
from transformers import BertTokenizer, BertConfig, BertModel

In [ ]:
# !pip install -i https://mirrors.cloud.tencent.com/pypi/simple transformers

In [3]:
tokenizer = BertTokenizer.from_pretrained('./opensource_models/chinese-roberta-wwm-ext', use_fast=True)

In [11]:
uni_bert_cfg = BertConfig.from_pretrained(f'./opensource_models/chinese-roberta-wwm-ext/config.json')
roberta = BertModel.from_pretrained('./opensource_models/chinese-roberta-wwm-ext', config=uni_bert_cfg)

Some weights of the model checkpoint at ./opensource_models/chinese-roberta-wwm-ext were not used when initializing BertModel: ['cls.predictions.transform.dense.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.decoder.weight', 'cls.predictions.decoder.bias', 'cls.predictions.bias', 'cls.seq_relationship.bias', 'cls.seq_relationship.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.LayerNorm.weight']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


In [12]:
for name,parameters in roberta.named_parameters():
    print(name,':',parameters.size())

embeddings.word_embeddings.weight : torch.Size([21128, 768])
embeddings.position_embeddings.weight : torch.Size([512, 768])
embeddings.token_type_embeddings.weight : torch.Size([2, 768])
embeddings.LayerNorm.weight : torch.Size([768])
embeddings.LayerNorm.bias : torch.Size([768])
encoder.layer.0.attention.self.query.weight : torch.Size([768, 768])
encoder.layer.0.attention.self.query.bias : torch.Size([768])
encoder.layer.0.attention.self.key.weight : torch.Size([768, 768])
encoder.layer.0.attention.self.key.bias : torch.Size([768])
encoder.layer.0.attention.self.value.weight : torch.Size([768, 768])
encoder.layer.0.attention.self.value.bias : torch.Size([768])
encoder.layer.0.attention.output.dense.weight : torch.Size([768, 768])
encoder.layer.0.attention.output.dense.bias : torch.Size([768])
encoder.layer.0.attention.output.LayerNorm.weight : torch.Size([768])
encoder.layer.0.attention.output.LayerNorm.bias : torch.Size([768])
encoder.layer.0.intermediate.dense.weight : torch.Size([3

In [27]:
for name,parameters in roberta.named_parameters():
    if name == 'encoder.layer.0.attention.self.query.weight':
        print(parameters)

Parameter containing:
tensor([[ 0.0793,  0.0618,  0.0060,  ...,  0.0747, -0.0021, -0.0419],
        [-0.0290, -0.0252,  0.0010,  ...,  0.0236, -0.0013,  0.0130],
        [-0.0425,  0.0177, -0.0039,  ...,  0.0832,  0.0110,  0.0326],
        ...,
        [-0.0897,  0.0308, -0.0503,  ...,  0.0606,  0.0597,  0.0533],
        [-0.0537, -0.0717, -0.0139,  ..., -0.0276,  0.0464, -0.0401],
        [ 0.0033, -0.0356,  0.0059,  ...,  0.1179, -0.0157, -0.0453]],
       requires_grad=True)


In [21]:
uni_bert_cfg = BertConfig.from_pretrained(f'./opensource_models/chinese-roberta-wwm-ext/config.json')
roberta2 = UniBertForMaskedLM.from_pretrained('./opensource_models/chinese-roberta-wwm-ext', config=uni_bert_cfg)

Some weights of the model checkpoint at ./opensource_models/chinese-roberta-wwm-ext were not used when initializing UniBertForMaskedLM: ['cls.seq_relationship.weight', 'cls.seq_relationship.bias', 'bert.pooler.dense.bias', 'bert.pooler.dense.weight']
- This IS expected if you are initializing UniBertForMaskedLM from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing UniBertForMaskedLM from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of UniBertForMaskedLM were not initialized from the model checkpoint at ./opensource_models/chinese-roberta-wwm-ext and are newly initialized: ['bert.video_dense.bias', 'bert.video_dense.weight']
You should probably TRAIN this model on a down-stream task to be able

In [24]:
for name,parameters in roberta2.named_parameters():
    print(name,':',parameters.size())

bert.embeddings.word_embeddings.weight : torch.Size([21128, 768])
bert.embeddings.position_embeddings.weight : torch.Size([512, 768])
bert.embeddings.token_type_embeddings.weight : torch.Size([2, 768])
bert.embeddings.LayerNorm.weight : torch.Size([768])
bert.embeddings.LayerNorm.bias : torch.Size([768])
bert.video_dense.weight : torch.Size([768, 768])
bert.video_dense.bias : torch.Size([768])
bert.encoder.layer.0.attention.self.query.weight : torch.Size([768, 768])
bert.encoder.layer.0.attention.self.query.bias : torch.Size([768])
bert.encoder.layer.0.attention.self.key.weight : torch.Size([768, 768])
bert.encoder.layer.0.attention.self.key.bias : torch.Size([768])
bert.encoder.layer.0.attention.self.value.weight : torch.Size([768, 768])
bert.encoder.layer.0.attention.self.value.bias : torch.Size([768])
bert.encoder.layer.0.attention.output.dense.weight : torch.Size([768, 768])
bert.encoder.layer.0.attention.output.dense.bias : torch.Size([768])
bert.encoder.layer.0.attention.output.L

In [28]:
for name,parameters in roberta2.named_parameters():
    if name == 'bert.encoder.layer.0.attention.self.query.weight':
        print(parameters)

Parameter containing:
tensor([[ 0.0793,  0.0618,  0.0060,  ...,  0.0747, -0.0021, -0.0419],
        [-0.0290, -0.0252,  0.0010,  ...,  0.0236, -0.0013,  0.0130],
        [-0.0425,  0.0177, -0.0039,  ...,  0.0832,  0.0110,  0.0326],
        ...,
        [-0.0897,  0.0308, -0.0503,  ...,  0.0606,  0.0597,  0.0533],
        [-0.0537, -0.0717, -0.0139,  ..., -0.0276,  0.0464, -0.0401],
        [ 0.0033, -0.0356,  0.0059,  ...,  0.1179, -0.0157, -0.0453]],
       requires_grad=True)


In [34]:
encoded_titles = tokenizer('', 
                           max_length=20, 
                           padding='max_length', 
                           truncation=True, 
                           add_special_tokens=False,
                          )

In [35]:
encoded_titles

{'input_ids': [], 'token_type_ids': [], 'attention_mask': []}

In [27]:
len(encoded_titles['input_ids']), len(encoded_titles['token_type_ids']), len(encoded_titles['token_type_ids'])

(20, 20, 20)

In [32]:
encoded_titles['input_ids']

[101, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [33]:
[0] * 84

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [29]:
import logging
import os
import time
import torch
import numpy as np

from config import parse_args
from data_helper.data_helper import create_dataloaders

from util import setup_device, setup_seed, setup_logging, setup_pretrain, build_optimizer, evaluate, build_optimizer2
from util import EMA, FGM

from models.doublestream_model import MultiModal
from models.singlestream_model import SingleStream_model
from models.singlestream_with_pretrain_model import SingleStream_model_pretrain, UniBertForMaskedLM,UniBert3


from tqdm import tqdm

import warnings
warnings.filterwarnings('ignore')

In [18]:
# !pip install -i https://mirrors.cloud.tencent.com/pypi/simple timm

Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://mirrors.cloud.tencent.com/pypi/simple
     |████████████████████████████████| 512 kB 797 kB/s            


0

In [ ]:
uni_bert_cfg = BertConfig.from_pretrained(f'{args.bert_dir}/config.json')
roberta2 = UniBertForMaskedLM.from_pretrained(args.bert_dir, config=uni_bert_cfg)

In [30]:
uni_bert_cfg = BertConfig.from_pretrained(f'./opensource_models/chinese-roberta-wwm-ext/config.json')
UniBert3 = UniBert3(config=uni_bert_cfg)

In [31]:
for name,parameters in UniBert3.named_parameters():
    print(name,':',parameters.size())

embeddings.word_embeddings.weight : torch.Size([21128, 768])
embeddings.position_embeddings.weight : torch.Size([512, 768])
embeddings.token_type_embeddings.weight : torch.Size([2, 768])
embeddings.LayerNorm.weight : torch.Size([768])
embeddings.LayerNorm.bias : torch.Size([768])
video_dense.weight : torch.Size([768, 768])
video_dense.bias : torch.Size([768])
encoder.layer.0.attention.self.query.weight : torch.Size([768, 768])
encoder.layer.0.attention.self.query.bias : torch.Size([768])
encoder.layer.0.attention.self.key.weight : torch.Size([768, 768])
encoder.layer.0.attention.self.key.bias : torch.Size([768])
encoder.layer.0.attention.self.value.weight : torch.Size([768, 768])
encoder.layer.0.attention.self.value.bias : torch.Size([768])
encoder.layer.0.attention.output.dense.weight : torch.Size([768, 768])
encoder.layer.0.attention.output.dense.bias : torch.Size([768])
encoder.layer.0.attention.output.LayerNorm.weight : torch.Size([768])
encoder.layer.0.attention.output.LayerNorm.b

In [32]:
for name,parameters in UniBert3.named_parameters():
    if name == 'embeddings.word_embeddings.weight':
        print(parameters)

Parameter containing:
tensor([[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [ 0.0351,  0.0032, -0.0068,  ...,  0.0028,  0.0174, -0.0056],
        [ 0.0228, -0.0011,  0.0035,  ...,  0.0156, -0.0159, -0.0477],
        ...,
        [-0.0089,  0.0028, -0.0108,  ..., -0.0300, -0.0222, -0.0032],
        [-0.0328, -0.0159, -0.0049,  ..., -0.0208, -0.0162,  0.0058],
        [ 0.0068,  0.0005, -0.0600,  ..., -0.0119, -0.0065, -0.0229]],
       requires_grad=True)


In [3]:
import torch
# 新增：
import torch.distributed as dist

In [5]:
torch.__version__

'1.9.0'

In [4]:
dist.init_process_group(backend='nccl') 

ValueError: Error initializing torch.distributed using env:// rendezvous: environment variable RANK expected, but not set

In [2]:
torch.distributed.get_world_size()

RuntimeError: Default process group has not been initialized, please make sure to call init_process_group.